//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tinhGiot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tinhGiot.Resources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn vào giỏ.
        /// </summary>
        public static string AddToBag {
            get {
                return ResourceManager.GetString("AddToBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám Phá.
        /// </summary>
        public static string Banner1_Action {
            get {
                return ResourceManager.GetString("Banner1_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinh dầu từ các loại thảo mộc quen thuộc .
        /// </summary>
        public static string Banner1_Text {
            get {
                return ResourceManager.GetString("Banner1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinh Túy Từ Thảo Mộc.
        /// </summary>
        public static string Banner1_Title {
            get {
                return ResourceManager.GetString("Banner1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Hiểu Thêm.
        /// </summary>
        public static string Banner2_Action {
            get {
                return ResourceManager.GetString("Banner2_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc trưng tinh dầu nhũ hương của Tinh Giọt.
        /// </summary>
        public static string Banner2_Text {
            get {
                return ResourceManager.GetString("Banner2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhũ Hương.
        /// </summary>
        public static string Banner2_Title {
            get {
                return ResourceManager.GetString("Banner2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc Thêm.
        /// </summary>
        public static string Banner3_Action {
            get {
                return ResourceManager.GetString("Banner3_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết hợp đặc tính các loại tinh dầu tạo mùi hương theo sở thích riêng.
        /// </summary>
        public static string Banner3_Text {
            get {
                return ResourceManager.GetString("Banner3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinh Dầu Tạo Mùi Hương.
        /// </summary>
        public static string Banner3_Title {
            get {
                return ResourceManager.GetString("Banner3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Hiểu Thêm.
        /// </summary>
        public static string Banner4_Action {
            get {
                return ResourceManager.GetString("Banner4_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinh dầu gắn liền với cuộc sống vừa giúp thư giãn vừa duy trì sức khỏe..
        /// </summary>
        public static string Banner4_Text {
            get {
                return ResourceManager.GetString("Banner4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinh Dầu Mang Lại Lợi Ích Gì?.
        /// </summary>
        public static string Banner4_Title {
            get {
                return ResourceManager.GetString("Banner4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài Viết.
        /// </summary>
        public static string Blogs {
            get {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinh dầu.
        /// </summary>
        public static string EssentialOil {
            get {
                return ResourceManager.GetString("EssentialOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinh-dầu.
        /// </summary>
        public static string EssentialOil_url {
            get {
                return ResourceManager.GetString("EssentialOil_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xông tinh dầu.
        /// </summary>
        public static string EssentialOilBurner {
            get {
                return ResourceManager.GetString("EssentialOilBurner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xông-tinh-dầu.
        /// </summary>
        public static string EssentialOilBurner_url {
            get {
                return ResourceManager.GetString("EssentialOilBurner_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám Phá.
        /// </summary>
        public static string ExploringProduct {
            get {
                return ResourceManager.GetString("ExploringProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhũ hương và Mộc dược.
        /// </summary>
        public static string FrankincenseMyrrha {
            get {
                return ResourceManager.GetString("FrankincenseMyrrha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhũ hương và mộc dược là hai dược liệu dùng trong đông y trong việc điều trị đau nhức và hoạt huyết.  Quan trọng trong đời sống tâm linh được dùng để xông trong các nghi lễ được từ sử dụng từ xưa....
        /// </summary>
        public static string FrankincenseMyrrha_Description {
            get {
                return ResourceManager.GetString("FrankincenseMyrrha_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gừng.
        /// </summary>
        public static string Ginger {
            get {
                return ResourceManager.GetString("Ginger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gừng có tính ấm và vị cay nhẹ,  rất tốt cho hỗ trợ tiêu hóa.  Gừng tươi vài lát ủ như trà và dùng uống, với tinh dầu thì chỉ cần một giọt cho vài ly nóng có thể thưởng thức hương gừng xông trước khi uống ....
        /// </summary>
        public static string Ginger_Description {
            get {
                return ResourceManager.GetString("Ginger_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinh Giot mong muốn chia sẽ niềm đam mê về tinh dầu đến với mọi người.  Để cảm nhận sự tinh túy và gần gũi từ thiên nhiên,  Tinh giọt chọn chất lượng sản phẩm hoàn toàn chiết từ nguồn gốc các phần của thảo mộc dược..
        /// </summary>
        public static string Header_Description {
            get {
                return ResourceManager.GetString("Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tinh dầu, sả, gừng,trái chúc, chanh thái, lá chúc, lá chanh thái, nhũ hương, mộc dược, trầm ý, trầm châu phi, trầm hương,carterii, sacra, papyreifera,neglecta.
        /// </summary>
        public static string Header_Keywords {
            get {
                return ResourceManager.GetString("Header_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinh dầu thảo mộc dược nguồn nguyên liệu sẵn có trong thiên nhiên chiết xuất theo lôi cuốn hơi nước.  Các loại thảo mộc dươc chúng ta rất gần gũi trong cuộc sống qua ẩm thực và dùng trong các phương thuốc dân gian..
        /// </summary>
        public static string Header_Title {
            get {
                return ResourceManager.GetString("Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm Thông Dụng .
        /// </summary>
        public static string HotItem {
            get {
                return ResourceManager.GetString("HotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nước cất tinh dầu.
        /// </summary>
        public static string Hydrosol {
            get {
                return ResourceManager.GetString("Hydrosol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nước-cất-tinh-dầu.
        /// </summary>
        public static string Hydrosol_url {
            get {
                return ResourceManager.GetString("Hydrosol_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hương xông và đốt.
        /// </summary>
        public static string Incense {
            get {
                return ResourceManager.GetString("Incense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hương-xông-đốt.
        /// </summary>
        public static string Incense_url {
            get {
                return ResourceManager.GetString("Incense_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xông hương.
        /// </summary>
        public static string IncenseBurner {
            get {
                return ResourceManager.GetString("IncenseBurner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xông-hương.
        /// </summary>
        public static string IncenseBurner_url {
            get {
                return ResourceManager.GetString("IncenseBurner_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhang.
        /// </summary>
        public static string IncenseStick {
            get {
                return ResourceManager.GetString("IncenseStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhang.
        /// </summary>
        public static string IncenseStick_url {
            get {
                return ResourceManager.GetString("IncenseStick_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sả.
        /// </summary>
        public static string Lemongrass {
            get {
                return ResourceManager.GetString("Lemongrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng ta rất quen thuộc với cây sả không thể thiếu trong các món ăn truyền thống.  Bên cạnh đó, sả cũng dùng cho xông hơi và nhiều mục đích khác....
        /// </summary>
        public static string Lemongrass_Description {
            get {
                return ResourceManager.GetString("Lemongrass_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn Cần Tìm ...!?.
        /// </summary>
        public static string LookingFor {
            get {
                return ResourceManager.GetString("LookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lá Chúc.
        /// </summary>
        public static string MakrutLeaf {
            get {
                return ResourceManager.GetString("MakrutLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lá chúc hay còn gọi lá chanh Thái, gần đây được sử dụng rộng rãi trong các món ăn đặc biệt kết hợp trong món ăn với gà.  Lá chúc có mùi đặc trưng khác hẳn so với lá chanh thông thường....
        /// </summary>
        public static string MakrutLeaf_Description {
            get {
                return ResourceManager.GetString("MakrutLeaf_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trái Chúc.
        /// </summary>
        public static string MakrutLime {
            get {
                return ResourceManager.GetString("MakrutLime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trái Chúc có mùi thơm nồng hơn chanh, vỏ sần sùi và dầy, ở Việt Nam được trồng rộng rãi ở vùng Tịnh Biên, Tri Tôn Ba Chúc.  Trái Chúc là tên gọi theo địa phương, tên gọi khác có thể là chanh Thái....
        /// </summary>
        public static string MakrutLime_Description {
            get {
                return ResourceManager.GetString("MakrutLime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chăm sóc và làm đẹp.
        /// </summary>
        public static string PersonalSkinCare {
            get {
                return ResourceManager.GetString("PersonalSkinCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chăm-sóc-làm-đẹp.
        /// </summary>
        public static string PersonalSkineCare_url {
            get {
                return ResourceManager.GetString("PersonalSkineCare_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Thêm.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nến.
        /// </summary>
        public static string Tealight {
            get {
                return ResourceManager.GetString("Tealight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nến.
        /// </summary>
        public static string Tealight_url {
            get {
                return ResourceManager.GetString("Tealight_url", resourceCulture);
            }
        }
    }
}
