//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tinhGiot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProcessCheckout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessCheckout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tinhGiot.Resources.ProcessCheckout", typeof(ProcessCheckout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đăng ký chưa có..
        /// </summary>
        public static string Account_Email_message {
            get {
                return ResourceManager.GetString("Account_Email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và Tên.
        /// </summary>
        public static string Account_Fullname {
            get {
                return ResourceManager.GetString("Account_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và Tên đăng ký chưa có..
        /// </summary>
        public static string Account_Fullname_message {
            get {
                return ResourceManager.GetString("Account_Fullname_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Account_Phonenumber {
            get {
                return ResourceManager.GetString("Account_Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện đăng ký chưa có..
        /// </summary>
        public static string Account_Phonenumber_message {
            get {
                return ResourceManager.GetString("Account_Phonenumber_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi địa chỉ giao hàng.
        /// </summary>
        public static string ChangeDeliveryAddress {
            get {
                return ResourceManager.GetString("ChangeDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí giao hàng thay đổi theo thay đổi quốc gia nơi đến.
        /// </summary>
        public static string ChangeDeliveryCost {
            get {
                return ResourceManager.GetString("ChangeDeliveryCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt Hàng.
        /// </summary>
        public static string CompleteOrder {
            get {
                return ResourceManager.GetString("CompleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian đặt hàng:.
        /// </summary>
        public static string DateTimeOrder {
            get {
                return ResourceManager.GetString("DateTimeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ nhà.
        /// </summary>
        public static string Delivery_Address {
            get {
                return ResourceManager.GetString("Delivery_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ nhà để giao nhận chưa có..
        /// </summary>
        public static string Delivery_Address_message {
            get {
                return ResourceManager.GetString("Delivery_Address_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/S ĐỊA CHỈ GIAO NHẬN.
        /// </summary>
        public static string Delivery_AddressList {
            get {
                return ResourceManager.GetString("Delivery_AddressList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gởi theo quà tặng.
        /// </summary>
        public static string Delivery_AsGift {
            get {
                return ResourceManager.GetString("Delivery_AsGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố/Tỉnh.
        /// </summary>
        public static string Delivery_City {
            get {
                return ResourceManager.GetString("Delivery_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố để giao nhận chưa có..
        /// </summary>
        public static string Delivery_City_message {
            get {
                return ResourceManager.GetString("Delivery_City_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí vận chuyển.
        /// </summary>
        public static string Delivery_Cost {
            get {
                return ResourceManager.GetString("Delivery_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        public static string Delivery_Country {
            get {
                return ResourceManager.GetString("Delivery_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giao nhận.
        /// </summary>
        public static string Delivery_Detail {
            get {
                return ResourceManager.GetString("Delivery_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string Delivery_District {
            get {
                return ResourceManager.GetString("Delivery_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận để giao nhận chưa có..
        /// </summary>
        public static string Delivery_District_message {
            get {
                return ResourceManager.GetString("Delivery_District_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và Tên người nhận.
        /// </summary>
        public static string Delivery_Fullname {
            get {
                return ResourceManager.GetString("Delivery_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và Tên để giao nhận chưa có..
        /// </summary>
        public static string Delivery_Fullname_message {
            get {
                return ResourceManager.GetString("Delivery_Fullname_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lời nhắn quà tặng.
        /// </summary>
        public static string Delivery_GiftMessage {
            get {
                return ResourceManager.GetString("Delivery_GiftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lời chúc quà tặng mà chưa có..
        /// </summary>
        public static string Delivery_GiftMessage_message {
            get {
                return ResourceManager.GetString("Delivery_GiftMessage_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú giao hàng.
        /// </summary>
        public static string Delivery_Note {
            get {
                return ResourceManager.GetString("Delivery_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại người nhận.
        /// </summary>
        public static string Delivery_Phonenumber {
            get {
                return ResourceManager.GetString("Delivery_Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại để giao nhận chưa có..
        /// </summary>
        public static string Delivery_Phonenumber_message {
            get {
                return ResourceManager.GetString("Delivery_Phonenumber_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bưu điện.
        /// </summary>
        public static string Delivery_Postcode {
            get {
                return ResourceManager.GetString("Delivery_Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường/Xã.
        /// </summary>
        public static string Delivery_Ward {
            get {
                return ResourceManager.GetString("Delivery_Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường để giao nhận chưa có..
        /// </summary>
        public static string Delivery_Ward_message {
            get {
                return ResourceManager.GetString("Delivery_Ward_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí giao hàng :.
        /// </summary>
        public static string DeliveryCost {
            get {
                return ResourceManager.GetString("DeliveryCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá:.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo đặt hàng Tinh Giọt.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc số điện đã sử dụng.
        /// </summary>
        public static string Exist_Email_Phonenumber {
            get {
                return ResourceManager.GetString("Exist_Email_Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí giao hàng.
        /// </summary>
        public static string FreeShip {
            get {
                return ResourceManager.GetString("FreeShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và Tên: .
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các ghi chú.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng mới.
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công đặt hàng.
        /// </summary>
        public static string Order_Success {
            get {
                return ResourceManager.GetString("Order_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công đặt hàng và tiếp tục xác nhận phần thanh toán..
        /// </summary>
        public static string Order_Success_Pending_Payment {
            get {
                return ResourceManager.GetString("Order_Success_Pending_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Đã thanh toán.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức thanh toán.
        /// </summary>
        public static string Payment_Method {
            get {
                return ResourceManager.GetString("Payment Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại:  .
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slg:.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm lược giỏ hàng.
        /// </summary>
        public static string ShoppingBag {
            get {
                return ResourceManager.GetString("ShoppingBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T/tiền:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Còn lại:.
        /// </summary>
        public static string TotalPayment {
            get {
                return ResourceManager.GetString("TotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Chưa thanh toán.
        /// </summary>
        public static string Unpaid {
            get {
                return ResourceManager.GetString("Unpaid", resourceCulture);
            }
        }
    }
}
